version: '3.3'
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "Pip3Quinn"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "2717:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/var/run/docker.sock mongodb/mongodb
      - /var/run/docker.sock:/var/run/docker.sock

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  imdbFileSync:
    build: filesync/
    image: paul/filesync:1.0-SNAPSHOT
    depends_on:
      - mongodb
    volumes:
      - imdb_file_data:/var/lib/imdb/data/files
  mq:
    container_name: rabbitMQ
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitMQ_data:/var/lib/rabbitmq/data

  webService:
    build: webservice/
    image: paul/webservice:1.0-SNAPSHOT
    ports:
      - "8090:8090"
    depends_on:
      - db
      - mq
    env_file:
      - config/.dev

  ui:
    hostname: localhost
    build: ui/
    image: paul/ui:latest
    ports:
      - "4200:4200"

  portainer:
    image: portainer/portainer-ce
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: always
    volumes:
      - portainer_data:/var/run/docker.sock portainer/portainer-ce
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
    external: false
  portainer_data:
    external: false
  rabbitMQ_data:
    external: false
  mongo_data:
    external: false
  imdb_file_data:
    external: false


