# Use postgres/example user/password credentials
# version: "3.1"
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pip3Quinn
      PG_MAJOR: 13
      PG_VERSION: 13.3-1.pgdg100+1

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080

  portainer-instance:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000
      - 9000:9000

  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret cookie here"
    ports:
      - 15672:15672
      - 5672:5672