from enum import Enum


class Profession(Enum):
    SOUNDTRACK = 'SOUNDTRACK',
    ACTOR = 'ACTOR',
    ACTRESS = 'ACTRESS',
    MISCELLANEOUS = 'MISCELLANEOUS',
    PRODUCER = 'PRODUCER',
    DIRECTOR = 'DIRECTOR',
    WRITER = 'WRITER',
    MUSIC_DEPARTMENT = 'MUSIC-DEPARTMENT',
    MAKE_UP_DEPARTMENT = 'MAKE-UP-DEPARTMENT',
    ASSISTANT_DIRECTOR = 'ASSISTANT-DIRECTOR',
    COMPOSER = 'COMPOSER'
