name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Branch
      run: git config --global init.defaultBranch main
    - name: Build the Docker image
      working-directory: ./webservice/
      run: docker build  .\webservice --file Dockerfile --tag webservice:$(date +%s)
